name: 'Chrome Addon Action'
description: 'Upload your addon to the Chrome Web Store'
author: 'Thomas McNiven'
inputs:
  extension:
    description: 'ID of the extension that you are updating'
  zip:
    description: 'Path to a .zip of your addon'
  service:
    description: 'Your Google API service account JSON data'
  publisher:
    description: 'An email address that has publishing authority for this extension'
runs:
  using: 'node12'
  main: 'lib/main.js'
