name: 'Chrome Addon Action'
description: 'Upload your addon to the Chrome Web Store'
author: 'Thomas McNiven'
inputs:
  extension:
    description: 'ID of the extension that you are updating'
  zip:
    description: 'Path to a .zip of your addon'
  client-id:
    description: 'Google OAuth2 client id'
  client-secret:
    description: 'Google OAuth2 client secret'
  refresh-token:
    description: 'Google OAuth2 refresh token'
  publishTarget:
    required: false
    default: 'default'
    description: 'The visibility of the addon (see Chrome Web Store Publish API for more info)'
runs:
  using: 'node12'
  main: 'lib/main.js'
